<a href="https://colab.research.google.com/github/nellyn94/BlockChainDemo/blob/main/00_tensorflow_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this notebook, we are going to cover some of the most fundamental concepts of tensor using TensorFlow
More specifically ,we are going to cover:
* Introduction to tensor 
* getting info from tensor
* Manioulating tensor 
* Tensor and Numpy
* Using @tf.function(a way to speed up your regular Python functions)
* Using GPUs with TensorFow (or TPU)
* Exercises to try for myself


# Introduction to Tensor 

In [6]:
# Import TensorFlow 
import tensorflow as tf
print(tf.__version__)

2.4.1


In [7]:
#Creating tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
#Check the number of dimentions of a tensor(ndim for number dimensions)
scalar.ndim

0

In [9]:
#Create a vector 
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [10]:
#check the dimention of our vectror 
vector.ndim

1

In [15]:
#Create a matrix
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [16]:
matrix.ndim

2

In [19]:
#Create another matrix 
another_matrix = tf.constant([[10., 7.],
                              [3.,2.],
                              [8., 9.]], dtype=tf.float16)# specify data type with ditype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [20]:
#what's the number dimentions of another_matrix
another_matrix.ndim

2

In [21]:
#lets create a tensor 
tensor = tf.constant([[[1,2,3,],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                       [[13,14,15],
                        [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [22]:
tensor.ndim

3

What we've creater so far:
* Scalar: a single number 
* Vector: a number with direction 
* Matrix: a 2-dimentional array of numbers 
* Tensor: an n-dimentional array of numbers (wheere n can be any number, a  0- dimentional is a scalar, a 1-dimesional is a vector)

### Creating tensor with `tf.Variable`

In [23]:
#Create the same tensor with tf.Variable() as above 
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [25]:
# Let's try change one of the elements in our changeable tensor 
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [26]:
# how about we try .assing()
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [27]:
# Let's try change our unchageable tensor
unchangeable_tensor[0].assign(7)

AttributeError: ignored

**Note**: Rarely in practice you will need to decide whether to use `tf.constant` or `tf.variable` to create ensor, as TensorFlow does this foe you, However if in doubt, use `tf.constant` and change it later if needed.

Creating random Tensors

Random tensors are tensors of some abitrary size which contains numbers.

In [35]:
# Create two  random (but the same) tensors
random_1  = tf.random.Generator.from_seed(42)# set seed for reproducibility
random_1 = random_1.normal(shape= (3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape= (3,2))

# Are they equal?
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)